CREATE VIEW weather_data_converted AS
SELECT
    from_unixtime((CAST(time AS DOUBLE) - 25569) * 86400) AS converted_time,
    max_temp,
    min_temp,
    temp,
    wind_chill,
    heat_index,
    precip,
    snow,
    snow_depth,
    wind_speed,
    wind_direction,
    wind_gust,
    visibility,
    cloud_cover,
    humid,
    clear_cond,
    none_cond,
    overcast_cond,
    partially_cloudy_cond,
    rain_cond,
    snow_cond,
    month_sin,
    month_cos,
    day_sin,
    day_cos,
    hour_sin,
    hour_cos,
    minute_sin,
    minute_cos,
    day_of_week_sin,
    day_of_week_cos,
    dark,
    part_dark,
    light,
    holiday
FROM "default"."weather_data";
